version: '3.7'
services:
  app:
    env_file: .env
    build:
      context: "."
      dockerfile: dev.Dockerfile
    command: "air -c .air.toml"
    tty: true
    volumes:
      - .:/app
#      - ./credentials:/credentials/google-app-credentials
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/google-app-credentials/admin-service-account.json
      - DATASTORE_EMULATOR_HOST=datastore:8081
      - DATASTORE_PROJECT_ID=audity-api-dev
    depends_on:
      - datastore
  datastore:
    image: datastore-emulator
#    volumes:
#      - ./.datastore:/root/.config/gcloud/emulators/datastore
    environment:
      TZ: Asia/Tokyo
      PROJECT_ID: audity-api-dev
      PORT: 0.0.0.0:8081
#    command: |
#      gcloud beta emulators datastore start --project=audity-api-dev --host-port=0.0.0.0:8081